version: "4.25"

services:
  database:
    container_name: database
    image: postgres:12.8
    restart: always
    environment:
      - POSTGRES_USER=orr
      - POSTGRES_PASSWORD=pass1ord
      - POSTGRES_DB=ecom
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data 

volumes:
  db: